apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/abiycisco/demo77:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/abiycisco/demo77:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: demo77
        chartPath: charts/demo77
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/abiycisco/demo77'
          image.tag: '{{.DIGEST_HEX}}'
